FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/ghcr.io/astral-sh/uv:python3.12-bookworm-slim

WORKDIR /app

ARG UV_COMPILE_BYTECODE=0
ENV UV_COMPILE_BYTECODE=${UV_COMPILE_BYTECODE} \
    UV_LINK_MODE=copy \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

# ===== 系统依赖（不要 cache mount）=====
RUN set -eux; \
    sed -i 's|http://deb.debian.org/debian|https://repo.huaweicloud.com/debian|g' /etc/apt/sources.list.d/debian.sources; \
    apt-get update; \
    apt-get install -y --no-install-recommends build-essential libglib2.0-0 libglib2.0-dev \
    postgresql-client && \
    rm -rf /var/lib/apt/lists/*

# ===== Python 依赖 =====
COPY pyproject.toml uv.lock README.md ./
RUN uv sync
# ===== 项目代码 =====
COPY src/ ./src/
COPY alembic.ini ./
COPY docker/docker-entrypoint.sh ./docker/docker-entrypoint.sh

RUN uv pip install -e .
RUN chmod +x ./docker/docker-entrypoint.sh

ENTRYPOINT ["./docker/docker-entrypoint.sh"]