"""add source id column in context

Revision ID: 8c98386540b4
Revises: c4b2d1d39a5a
Create Date: 2026-01-22 17:25:51.054912

"""

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8c98386540b4"
down_revision: str | Sequence[str] | None = "c4b2d1d39a5a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "context",
        sa.Column("source_id", sa.UUID(), nullable=True, comment="关联的源ID"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("context", "source_id")
    # ### end Alembic commands ###
