"""change konwledge embedding

Revision ID: c4b2d1d39a5a
Revises: 0236573bfc43
Create Date: 2026-01-22 15:39:40.375526

"""

from collections.abc import Sequence
from typing import Union

from alembic import op
from pgvector.sqlalchemy import Vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c4b2d1d39a5a"
down_revision: str | Sequence[str] | None = "0236573bfc43"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "agent_task",
        "user_id",
        existing_type=sa.UUID(),
        nullable=False,
        existing_comment="关联的用户标识",
    )
    op.add_column(
        "context",
        sa.Column(
            "keywords",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="关键词",
        ),
    )
    op.add_column(
        "context",
        sa.Column("embedding_384", Vector(384), nullable=True, comment="384维向量嵌入"),
    )
    op.add_column(
        "context",
        sa.Column("embedding_768", Vector(768), nullable=True, comment="768维向量嵌入"),
    )
    op.add_column(
        "context",
        sa.Column(
            "embedding_1024", Vector(1024), nullable=True, comment="1024维向量嵌入"
        ),
    )
    op.add_column(
        "context",
        sa.Column(
            "embedding_1536", Vector(1536), nullable=True, comment="1536维向量嵌入"
        ),
    )
    op.add_column(
        "context",
        sa.Column(
            "meta",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="额外元数据",
        ),
    )
    op.drop_index(op.f("ix_context_app_id"), table_name="context")
    op.drop_index(op.f("ix_context_conversation_id"), table_name="context")
    op.drop_index(
        op.f("ix_context_embedding_hnsw"),
        table_name="context",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    op.create_index(
        "ix_context_embedding_1024_hnsw",
        "context",
        ["embedding_1024"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding_1024": "vector_cosine_ops"},
    )
    op.create_index(
        "ix_context_embedding_1536_hnsw",
        "context",
        ["embedding_1536"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding_1536": "vector_cosine_ops"},
    )
    op.create_index(
        "ix_context_embedding_384_hnsw",
        "context",
        ["embedding_384"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding_384": "vector_cosine_ops"},
    )
    op.create_index(
        "ix_context_embedding_768_hnsw",
        "context",
        ["embedding_768"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding_768": "vector_cosine_ops"},
    )
    op.drop_column("context", "embedding")
    op.drop_column("context", "metadata")
    op.drop_column("context", "source")
    op.drop_column("context", "conversation_id")
    op.drop_column("context", "app_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "context",
        sa.Column(
            "app_id",
            sa.UUID(),
            autoincrement=False,
            nullable=False,
            comment="关联的应用ID",
        ),
    )
    op.add_column(
        "context",
        sa.Column(
            "conversation_id",
            sa.UUID(),
            autoincrement=False,
            nullable=True,
            comment="关联的对话ID",
        ),
    )
    op.add_column(
        "context",
        sa.Column(
            "source",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
            comment="上下文来源",
        ),
    )
    op.add_column(
        "context",
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
            comment="额外元数据",
        ),
    )
    op.add_column(
        "context",
        sa.Column(
            "embedding",
            Vector(1536),
            autoincrement=False,
            nullable=True,
            comment="向量嵌入",
        ),
    )
    op.drop_index(
        "ix_context_embedding_768_hnsw",
        table_name="context",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding_768": "vector_cosine_ops"},
    )
    op.drop_index(
        "ix_context_embedding_384_hnsw",
        table_name="context",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding_384": "vector_cosine_ops"},
    )
    op.drop_index(
        "ix_context_embedding_1536_hnsw",
        table_name="context",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding_1536": "vector_cosine_ops"},
    )
    op.drop_index(
        "ix_context_embedding_1024_hnsw",
        table_name="context",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding_1024": "vector_cosine_ops"},
    )
    op.create_index(
        op.f("ix_context_embedding_hnsw"),
        "context",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    op.create_index(
        op.f("ix_context_conversation_id"), "context", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_context_app_id"), "context", ["app_id"], unique=False)
    op.drop_column("context", "meta")
    op.drop_column("context", "embedding_1536")
    op.drop_column("context", "embedding_1024")
    op.drop_column("context", "embedding_768")
    op.drop_column("context", "embedding_384")
    op.drop_column("context", "keywords")
    op.alter_column(
        "agent_task",
        "user_id",
        existing_type=sa.UUID(),
        nullable=True,
        existing_comment="关联的用户标识",
    )
    # ### end Alembic commands ###
