"""add app_id to event table

Revision ID: 32bf5fe1f194
Revises: 20260301_baseline
Create Date: 2026-02-13 21:09:40.892426

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '32bf5fe1f194'
down_revision: str | Sequence[str] | None = '20260301_baseline'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    # Add column IF NOT EXISTS (baseline may already include it)
    conn.execute(sa.text("""
        ALTER TABLE event ADD COLUMN IF NOT EXISTS app_id UUID;
        COMMENT ON COLUMN event.app_id IS '关联的应用ID';
    """))
    # Create FK only if it doesn't already exist
    conn.execute(sa.text("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.table_constraints AS tc
                JOIN information_schema.key_column_usage AS kcu
                    ON tc.constraint_name = kcu.constraint_name
                    AND tc.table_schema = kcu.table_schema
                WHERE tc.table_name = 'event'
                  AND tc.constraint_type = 'FOREIGN KEY'
                  AND kcu.column_name = 'app_id'
            ) THEN
                ALTER TABLE event
                ADD CONSTRAINT fk_event_app_id
                FOREIGN KEY (app_id) REFERENCES app(id) ON DELETE SET NULL;
            END IF;
        END $$;
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Dynamically find and drop the FK constraint on app_id (name was auto-generated as None)
    conn = op.get_bind()
    conn.execute(sa.text("""
        DO $$
        DECLARE
            _cname text;
        BEGIN
            SELECT tc.constraint_name INTO _cname
            FROM information_schema.table_constraints AS tc
            JOIN information_schema.key_column_usage AS kcu
                ON tc.constraint_name = kcu.constraint_name
                AND tc.table_schema = kcu.table_schema
            WHERE tc.table_name = 'event'
              AND tc.constraint_type = 'FOREIGN KEY'
              AND kcu.column_name = 'app_id';
            IF _cname IS NOT NULL THEN
                EXECUTE 'ALTER TABLE event DROP CONSTRAINT IF EXISTS ' || quote_ident(_cname);
            END IF;
        END $$;
    """))
    op.drop_column('event', 'app_id')
    # ### end Alembic commands ###
