"""remove some features from knowledge

Revision ID: 5a9d9c9e5999
Revises: k6f7g8h9i0j1
Create Date: 2026-03-25 13:32:09.330112

"""

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5a9d9c9e5999"
down_revision: str | Sequence[str] | None = "k6f7g8h9i0j1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    conn.execute(sa.text("DROP INDEX IF EXISTS ix_skill_user_id CASCADE"))
    conn.execute(sa.text("DROP INDEX IF EXISTS ix_skill_user_id_name CASCADE"))
    conn.execute(sa.text("DROP TABLE IF EXISTS skill CASCADE"))
    conn.execute(sa.text("ALTER TABLE knowledge DROP COLUMN IF EXISTS provider"))
    conn.execute(
        sa.text("ALTER TABLE knowledge DROP COLUMN IF EXISTS indexing_technique")
    )
    conn.execute(sa.text("ALTER TABLE knowledge DROP COLUMN IF EXISTS embedding_model"))
    conn.execute(sa.text("DROP INDEX IF EXISTS ix_tool_bundle_user_id CASCADE"))
    conn.execute(sa.text("DROP INDEX IF EXISTS ux_tool_bundle_inner_source CASCADE"))
    conn.execute(sa.text("DROP INDEX IF EXISTS ux_tool_bundle_mcp_user_source CASCADE"))
    conn.execute(sa.text("DROP INDEX IF EXISTS ux_tool_bundle_user_name CASCADE"))
    conn.execute(sa.text("DROP INDEX IF EXISTS ix_tool_bundle_item_bundle_id CASCADE"))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_tool_bundle_item_bundle_id"),
        "tool_bundle_item",
        ["bundle_id"],
        unique=False,
    )
    op.create_index(
        op.f("ux_tool_bundle_user_name"),
        "tool_bundle",
        ["user_id", "name"],
        unique=True,
        postgresql_where="((bundle_type)::text = 'user'::text)",
    )
    op.create_index(
        op.f("ux_tool_bundle_mcp_user_source"),
        "tool_bundle",
        ["user_id", "source"],
        unique=True,
        postgresql_where="((bundle_type)::text = 'mcp'::text)",
    )
    op.create_index(
        op.f("ux_tool_bundle_inner_source"),
        "tool_bundle",
        ["source"],
        unique=True,
        postgresql_where="((bundle_type)::text = 'inner'::text)",
    )
    op.create_index(
        op.f("ix_tool_bundle_user_id"), "tool_bundle", ["user_id"], unique=False
    )
    op.add_column(
        "knowledge",
        sa.Column(
            "embedding_model",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
            comment="嵌入模型",
        ),
    )
    op.add_column(
        "knowledge",
        sa.Column(
            "indexing_technique",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
            comment="索引技术",
        ),
    )
    op.add_column(
        "knowledge",
        sa.Column(
            "provider",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
            comment="知识库提供商",
        ),
    )
    op.create_table(
        "skill",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("glance", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("summary", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("path", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column("source_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "tags",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "meta",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "files",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("skill_pkey")),
    )
    op.create_index(
        op.f("ix_skill_user_id_name"), "skill", ["user_id", "name"], unique=False
    )
    op.create_index(op.f("ix_skill_user_id"), "skill", ["user_id"], unique=False)
    # ### end Alembic commands ###
