"""update skill struct

Revision ID: 72fe31b7a0c3
Revises: b9d940dc850a
Create Date: 2026-03-25 15:31:05.111429

"""

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "72fe31b7a0c3"
down_revision: str | Sequence[str] | None = "b9d940dc850a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("context", "keywords")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "context",
        sa.Column(
            "keywords",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
            comment="关键词（已弃用，请使用 tags）",
        ),
    )
    # ### end Alembic commands ###
