"""create workspace_context table

Revision ID: 7f5f41cd5b30
Revises: d53fb5f02f6b
Create Date: 2026-02-14 21:07:45.956972

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f5f41cd5b30'
down_revision: str | Sequence[str] | None = 'd53fb5f02f6b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(sa.text("""
        CREATE TABLE IF NOT EXISTS workspace_context (
            id UUID NOT NULL,
            workspace_id UUID NOT NULL,
            created_by UUID,
            path VARCHAR(1024),
            name VARCHAR(512) NOT NULL,
            content_type VARCHAR(128),
            content TEXT,
            s3_key VARCHAR(1024),
            size_bytes INTEGER,
            meta JSONB,
            is_deleted BOOLEAN NOT NULL,
            expires_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ,
            PRIMARY KEY (id),
            FOREIGN KEY (workspace_id) REFERENCES workspace(id) ON DELETE CASCADE
        )
    """))
    conn.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_ws_ctx_created_by ON workspace_context (created_by)"))
    conn.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_ws_ctx_expires ON workspace_context (expires_at)"))
    conn.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_ws_ctx_workspace ON workspace_context (workspace_id)"))
    conn.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_ws_ctx_workspace_path ON workspace_context (workspace_id, path)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ws_ctx_workspace_path', table_name='workspace_context')
    op.drop_index('ix_ws_ctx_workspace', table_name='workspace_context')
    op.drop_index('ix_ws_ctx_expires', table_name='workspace_context')
    op.drop_index('ix_ws_ctx_created_by', table_name='workspace_context')
    op.drop_table('workspace_context')
    # ### end Alembic commands ###
