"""

Revision ID: 8e930fc7b4e3
Revises: eb254ab4cc1b
Create Date: 2026-02-18 20:02:10.040235

"""

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8e930fc7b4e3"
down_revision: str | Sequence[str] | None = "eb254ab4cc1b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(
        sa.text("ALTER TABLE workspace_trigger ADD COLUMN IF NOT EXISTS user_id UUID")
    )
    conn.execute(
        sa.text("ALTER TABLE workspace_trigger ALTER COLUMN workspace_id DROP NOT NULL")
    )
    conn.execute(
        sa.text(
            "CREATE INDEX IF NOT EXISTS ix_workspace_trigger_user_id ON workspace_trigger (user_id)"
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    # Drop index IF EXISTS (may have already been dropped by a later migration's downgrade)
    conn.execute(sa.text("DROP INDEX IF EXISTS ix_workspace_trigger_user_id"))
    # Delete user-level rows (workspace_id IS NULL) before restoring NOT NULL constraint
    conn.execute(sa.text("DELETE FROM workspace_trigger WHERE workspace_id IS NULL"))
    op.alter_column(
        "workspace_trigger",
        "workspace_id",
        existing_type=sa.UUID(),
        nullable=False,
        comment="所属工作区ID",
        existing_comment="所属工作区ID（用户级模板时为 null）",
    )
    # Drop column IF EXISTS (may have already been dropped by a later migration's downgrade)
    conn.execute(sa.text("ALTER TABLE workspace_trigger DROP COLUMN IF EXISTS user_id"))
    # ### end Alembic commands ###
