"""remove summary from context

Revision ID: b9d940dc850a
Revises: 5a9d9c9e5999
Create Date: 2026-03-25 13:50:39.865375

"""

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b9d940dc850a"
down_revision: str | Sequence[str] | None = "5a9d9c9e5999"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("context", "summary")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "context",
        sa.Column(
            "summary",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment="概览摘要（概览层，结构化数据）",
        ),
    )
    # ### end Alembic commands ###
