"""add path and s3_key to context table

Revision ID: d53fb5f02f6b
Revises: 32bf5fe1f194
Create Date: 2026-02-14 21:04:47.694256

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd53fb5f02f6b'
down_revision: str | Sequence[str] | None = '32bf5fe1f194'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(sa.text("ALTER TABLE context ADD COLUMN IF NOT EXISTS path VARCHAR(1024)"))
    conn.execute(sa.text("ALTER TABLE context ADD COLUMN IF NOT EXISTS s3_key VARCHAR(1024)"))
    conn.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_context_path ON context (path)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_context_path', table_name='context')
    op.drop_column('context', 's3_key')
    op.drop_column('context', 'path')
    # ### end Alembic commands ###
