import {
  Bot,
  Brain,
  ChevronLeft,
  ChevronRight,
  Clock,
  Cpu,
  ExternalLink,
  FileOutput,
  FolderKanban,
  Home,
  Layers,
  Library,
  ListTodo,
  LogOut,
  MessageSquare,
  Moon,
  Pencil,
  Play,
  Plus,
  Save,
  Send,
  Settings,
  Sparkles,
  Sun,
  Trash2,
  Wrench,
  Zap,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export const APP_ICONS = {
  app: Bot,
  brand: Bot,
  chat: MessageSquare,
  collapse: ChevronLeft,
  context: Layers,
  delete: Trash2,
  edit: Pencil,
  expand: ChevronRight,
  home: Home,
  history: Clock,
  knowledge: Library,
  logout: LogOut,
  memory: Brain,
  model: Cpu,
  new: Plus,
  open: ExternalLink,
  results: FileOutput,
  runs: Play,
  save: Save,
  send: Send,
  settings: Settings,
  skill: Sparkles,
  tasks: ListTodo,
  themeDark: Moon,
  themeLight: Sun,
  tool: Wrench,
  trigger: Zap,
  workspace: FolderKanban,
} satisfies Record<string, LucideIcon>;
