"""add preprocess , chat model and embedding model

Revision ID: 477f1f668530
Revises: 7c14c5f39329
Create Date: 2026-01-23 22:17:41.000495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy.vector

# revision identifiers, used by Alembic.
revision: str = '477f1f668530'
down_revision: Union[str, Sequence[str], None] = '7c14c5f39329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_model',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False, comment='模型显示名称'),
                    sa.Column('description', sa.Text(), nullable=True, comment='模型描述'),
                    sa.Column('user_id', sa.UUID(), nullable=True, comment='创建者用户ID（系统级模型为空）'),
                    sa.Column('provider', sa.String(length=50), nullable=False,
                              comment='提供商: openai/anthropic/dashscope/ollama/azure/custom'),
                    sa.Column('model_id', sa.String(length=255), nullable=False,
                              comment='模型标识符: gpt-4/claude-3-opus/qwen-turbo'),
                    sa.Column('base_url', sa.String(length=500), nullable=True, comment='API基础URL'),
                    sa.Column('api_key_ref', sa.String(length=255), nullable=True,
                              comment='API密钥引用（存储密钥名称，非实际密钥）'),
                    sa.Column('max_tokens', sa.Integer(), nullable=True, comment='最大输出token数'),
                    sa.Column('context_window', sa.Integer(), nullable=True, comment='上下文窗口大小'),
                    sa.Column('supports_vision', sa.Boolean(), nullable=False, comment='是否支持视觉输入'),
                    sa.Column('supports_function_call', sa.Boolean(), nullable=False, comment='是否支持函数调用'),
                    sa.Column('supports_streaming', sa.Boolean(), nullable=False, comment='是否支持流式输出'),
                    sa.Column('default_temperature', sa.Float(), nullable=True, comment='默认温度'),
                    sa.Column('default_top_p', sa.Float(), nullable=True, comment='默认top_p'),
                    sa.Column('default_max_tokens', sa.Integer(), nullable=True, comment='默认最大输出token'),
                    sa.Column('input_price', sa.Float(), nullable=True, comment='输入价格（每1K tokens）'),
                    sa.Column('output_price', sa.Float(), nullable=True, comment='输出价格（每1K tokens）'),
                    sa.Column('currency', sa.String(length=10), nullable=False, comment='货币单位'),
                    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='额外配置参数'),
                    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='元数据'),
                    sa.Column('is_system', sa.Boolean(), nullable=False, comment='是否为系统预置模型'),
                    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否为默认模型'),
                    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用'),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('embedding_model',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False, comment='模型显示名称'),
                    sa.Column('description', sa.Text(), nullable=True, comment='模型描述'),
                    sa.Column('user_id', sa.UUID(), nullable=True, comment='创建者用户ID（系统级模型为空）'),
                    sa.Column('provider', sa.String(length=50), nullable=False,
                              comment='提供商: openai/dashscope/huggingface/ollama/custom'),
                    sa.Column('model_id', sa.String(length=255), nullable=False,
                              comment='模型标识符: text-embedding-3-small/text-embedding-v2/bge-large-zh'),
                    sa.Column('base_url', sa.String(length=500), nullable=True, comment='API基础URL'),
                    sa.Column('api_key_ref', sa.String(length=255), nullable=True,
                              comment='API密钥引用（存储密钥名称，非实际密钥）'),
                    sa.Column('dimension', sa.Integer(), nullable=False, comment='向量维度: 384/768/1024/1536'),
                    sa.Column('max_tokens', sa.Integer(), nullable=True, comment='最大输入token数'),
                    sa.Column('supports_batch', sa.Boolean(), nullable=False, comment='是否支持批量处理'),
                    sa.Column('batch_size', sa.Integer(), nullable=False, comment='默认批处理大小'),
                    sa.Column('normalize', sa.Boolean(), nullable=False, comment='是否归一化向量'),
                    sa.Column('distance_metric', sa.String(length=20), nullable=False,
                              comment='距离度量: cosine/euclidean/dot_product'),
                    sa.Column('price', sa.Float(), nullable=True, comment='价格（每1K tokens）'),
                    sa.Column('currency', sa.String(length=10), nullable=False, comment='货币单位'),
                    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='额外配置参数'),
                    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='元数据'),
                    sa.Column('is_system', sa.Boolean(), nullable=False, comment='是否为系统预置模型'),
                    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否为默认模型'),
                    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用'),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('preprocess',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False, comment='预处理方法名称'),
                    sa.Column('description', sa.Text(), nullable=True, comment='预处理方法描述'),
                    sa.Column('user_id', sa.UUID(), nullable=False, comment='创建者用户ID'),
                    sa.Column('chunking_strategy', sa.String(length=50), nullable=False,
                              comment='分块策略: fixed_size/semantic/sentence/paragraph'),
                    sa.Column('chunk_size', sa.Integer(), nullable=False, comment='分块大小（字符数）'),
                    sa.Column('chunk_overlap', sa.Integer(), nullable=False, comment='分块重叠（字符数）'),
                    sa.Column('separator', sa.String(length=100), nullable=True, comment='分隔符'),
                    sa.Column('remove_extra_whitespace', sa.Boolean(), nullable=False, comment='移除多余空白'),
                    sa.Column('remove_urls', sa.Boolean(), nullable=False, comment='移除URL'),
                    sa.Column('remove_emails', sa.Boolean(), nullable=False, comment='移除邮箱'),
                    sa.Column('lowercase', sa.Boolean(), nullable=False, comment='转换为小写'),
                    sa.Column('embedding_model', sa.String(length=255), nullable=True, comment='嵌入模型名称'),
                    sa.Column('embedding_dimension', sa.Integer(), nullable=True, comment='嵌入向量维度'),
                    sa.Column('parser_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True,
                              comment='解析器配置（针对不同文件类型）'),
                    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='额外元数据'),
                    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否为默认配置'),
                    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用'),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('knowledge',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False, comment='知识库名称'),
                    sa.Column('description', sa.Text(), nullable=True, comment='知识库描述'),
                    sa.Column('user_id', sa.UUID(), nullable=False, comment='创建知识库的用户ID'),
                    sa.Column('owner_id', sa.UUID(), nullable=True, comment='知识库所有者ID'),
                    sa.Column('provider', sa.String(length=50), nullable=False, comment='知识库提供商'),
                    sa.Column('indexing_technique', sa.String(length=50), nullable=False, comment='索引技术'),
                    sa.Column('embedding_model', sa.String(length=255), nullable=True, comment='嵌入模型'),
                    sa.Column('preprocess_id', sa.UUID(), nullable=True, comment='预处理配置ID'),
                    sa.Column('status', sa.String(length=20), nullable=False, comment='知识库状态'),
                    sa.Column('permission', sa.String(length=20), nullable=False, comment='权限设置'),
                    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='额外元数据'),
                    sa.Column('document_count', sa.Integer(), nullable=False, comment='文档数量'),
                    sa.Column('chunk_count', sa.Integer(), nullable=False, comment='分段数量'),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
                    sa.ForeignKeyConstraint(['preprocess_id'], ['preprocess.id'], ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('document',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('knowledge_id', sa.UUID(), nullable=False, comment='所属知识库ID'),
                    sa.Column('user_id', sa.UUID(), nullable=False, comment='上传文档的用户ID'),
                    sa.Column('file_hash', sa.String(length=64), nullable=True, comment='SHA256哈希，用于去重'),
                    sa.Column('original_name', sa.String(length=255), nullable=False, comment='原始文件名'),
                    sa.Column('object_key', sa.String(length=500), nullable=False, comment='S3对象键'),
                    sa.Column('file_url', sa.String(length=1000), nullable=True, comment='访问URL'),
                    sa.Column('file_size', sa.Integer(), nullable=False, comment='文件大小（字节）'),
                    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='MIME类型'),
                    sa.Column('storage_type', sa.String(length=20), nullable=False, comment='存储类型: s3/oss/local'),
                    sa.Column('bucket_name', sa.String(length=100), nullable=True, comment='存储桶名称'),
                    sa.Column('content', sa.Text(), nullable=True, comment='文档内容'),
                    sa.Column('reference_count', sa.Integer(), nullable=False, comment='引用计数，用于去重'),
                    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除'),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
                    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('file_hash')
                    )
    op.create_index('ix_document_created_at', 'document', ['created_at'], unique=False)
    op.create_index('ix_document_file_hash', 'document', ['file_hash'], unique=False)
    op.create_index('ix_document_user_id', 'document', ['user_id'], unique=False)
    op.create_table('chunk',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('document_id', sa.UUID(), nullable=False, comment='所属文档ID'),
                    sa.Column('user_id', sa.UUID(), nullable=False, comment='所属用户ID'),
                    sa.Column('position', sa.Integer(), nullable=False, comment='分段位置'),
                    sa.Column('content', sa.Text(), nullable=False, comment='分段内容'),
                    sa.Column('content_length', sa.Integer(), nullable=False, comment='内容长度'),
                    sa.Column('status', sa.String(length=20), nullable=False, comment='处理状态'),
                    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用'),
                    sa.Column('embedding_384', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True,
                              comment='384维向量嵌入 (MiniLM / E5-small / bge-small)'),
                    sa.Column('embedding_768', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True,
                              comment='768维向量嵌入 (BERT / bge-base / e5-base)'),
                    sa.Column('embedding_1024', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True,
                              comment='1024维向量嵌入 (bge-large / e5-large)'),
                    sa.Column('embedding_1536', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True,
                              comment='1536维向量嵌入 (OpenAI / DashScope)'),
                    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='分段元数据'),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
                    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_chunk_document_id', 'chunk', ['document_id'], unique=False)
    op.create_index('ix_chunk_embedding_1024_hnsw', 'chunk', ['embedding_1024'], unique=False, postgresql_using='hnsw',
                    postgresql_with={'m': 16, 'ef_construction': 64},
                    postgresql_ops={'embedding_1024': 'vector_cosine_ops'})
    op.create_index('ix_chunk_embedding_1536_hnsw', 'chunk', ['embedding_1536'], unique=False, postgresql_using='hnsw',
                    postgresql_with={'m': 16, 'ef_construction': 64},
                    postgresql_ops={'embedding_1536': 'vector_cosine_ops'})
    op.create_index('ix_chunk_embedding_384_hnsw', 'chunk', ['embedding_384'], unique=False, postgresql_using='hnsw',
                    postgresql_with={'m': 16, 'ef_construction': 64},
                    postgresql_ops={'embedding_384': 'vector_cosine_ops'})
    op.create_index('ix_chunk_embedding_768_hnsw', 'chunk', ['embedding_768'], unique=False, postgresql_using='hnsw',
                    postgresql_with={'m': 16, 'ef_construction': 64},
                    postgresql_ops={'embedding_768': 'vector_cosine_ops'})
    op.create_index('ix_chunk_status', 'chunk', ['status'], unique=False)
    op.create_index('ix_chunk_user_id', 'chunk', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunk_user_id', table_name='chunk')
    op.drop_index('ix_chunk_status', table_name='chunk')
    op.drop_index('ix_chunk_embedding_768_hnsw', table_name='chunk', postgresql_using='hnsw',
                  postgresql_with={'m': 16, 'ef_construction': 64},
                  postgresql_ops={'embedding_768': 'vector_cosine_ops'})
    op.drop_index('ix_chunk_embedding_384_hnsw', table_name='chunk', postgresql_using='hnsw',
                  postgresql_with={'m': 16, 'ef_construction': 64},
                  postgresql_ops={'embedding_384': 'vector_cosine_ops'})
    op.drop_index('ix_chunk_embedding_1536_hnsw', table_name='chunk', postgresql_using='hnsw',
                  postgresql_with={'m': 16, 'ef_construction': 64},
                  postgresql_ops={'embedding_1536': 'vector_cosine_ops'})
    op.drop_index('ix_chunk_embedding_1024_hnsw', table_name='chunk', postgresql_using='hnsw',
                  postgresql_with={'m': 16, 'ef_construction': 64},
                  postgresql_ops={'embedding_1024': 'vector_cosine_ops'})
    op.drop_index('ix_chunk_document_id', table_name='chunk')
    op.drop_table('chunk')
    op.drop_index('ix_document_user_id', table_name='document')
    op.drop_index('ix_document_file_hash', table_name='document')
    op.drop_index('ix_document_created_at', table_name='document')
    op.drop_table('document')
    op.drop_table('knowledge')
    op.drop_table('preprocess')
    op.drop_table('embedding_model')
    op.drop_table('chat_model')
    # ### end Alembic commands ###
