

DIFY_BEARER_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMmM0Y2ExMGQtNzlkMS00NjhhLWI5MzMtNzg3NGI5MTA4YmQ4IiwiZXhwIjoxNzUwMzA1NzYyLCJpc3MiOiJTRUxGX0hPU1RFRCIsInN1YiI6IkNvbnNvbGUgQVBJIFBhc3Nwb3J0In0.L4MTA-LV9eQxx5LJbJCwflBAYop3RMS-3nVTdQShDgw"

HEADERS = {
    "Authorization": f"Bearer {DIFY_BEARER_TOKEN}"
}
