"""make admin_id nullable in tenant

Revision ID: 0430e7390877
Revises: 593829819d41
Create Date: 2025-12-24 16:08:04.480324

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0430e7390877'
down_revision: str | Sequence[str] | None = '593829819d41'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_task', 'app_id',
               existing_type=sa.UUID(),
               comment='关联的agent标识',
               existing_nullable=False)
    op.alter_column('agent_task', 'task_type',
               existing_type=sa.VARCHAR(),
               comment='任务类型',
               existing_nullable=True)
    op.alter_column('agent_task', 'status',
               existing_type=sa.VARCHAR(),
               comment='任务状态: pending, running, success, failed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('agent_task', 'text_message',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='任务输入数据',
               existing_nullable=True)
    op.alter_column('agent_task', 'result',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='任务结果',
               existing_nullable=True)
    op.alter_column('agent_task', 'error',
               existing_type=sa.TEXT(),
               comment='错误信息',
               existing_nullable=True)
    op.alter_column('agent_task', 'progress',
               existing_type=sa.INTEGER(),
               comment='任务进度百分比',
               existing_nullable=True)
    op.alter_column('agent_task', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('agent_task', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=True)
    op.alter_column('agent_task', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='开始执行时间',
               existing_nullable=True)
    op.alter_column('agent_task', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='完成时间',
               existing_nullable=True)
    # Drop constraint only if it exists
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conname = 'fk_agent_task_app'
                AND conrelid = 'agent_task'::regclass
            ) THEN
                ALTER TABLE agent_task DROP CONSTRAINT fk_agent_task_app;
            END IF;
        END $$;
    """)
    op.alter_column('agent_template', 'template_code',
               existing_type=sa.VARCHAR(),
               comment='模板标识',
               existing_nullable=False)
    op.alter_column('agent_template', 'template_name',
               existing_type=sa.VARCHAR(),
               comment='模板名称',
               existing_nullable=False)
    op.alter_column('agent_template', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='是否启用',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('agent_template', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Agent参数配置',
               existing_nullable=True)
    op.alter_column('agent_template', 'version',
               existing_type=sa.INTEGER(),
               comment='版本号',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('agent_template', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('agent_template', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=True)
    op.alter_column('app', 'app_code',
               existing_type=sa.VARCHAR(),
               comment='对外使用的agent标识',
               existing_nullable=False)
    op.alter_column('app', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment='是否启用',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('app', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Agent参数配置',
               existing_nullable=True)
    op.alter_column('app', 'version',
               existing_type=sa.INTEGER(),
               comment='版本号',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('app', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('app', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=True)
    op.alter_column('auth_tenant', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='租户名称',
               existing_nullable=False)
    op.alter_column('auth_tenant', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False,
               comment='租户描述')
    op.alter_column('auth_tenant', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否激活',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('auth_tenant', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='创建时间')
    op.alter_column('auth_tenant', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='更新时间')
    op.alter_column('auth_tenant', 'admin_id',
               existing_type=sa.UUID(),
               comment='管理员ID',
               existing_nullable=True)
    op.alter_column('auth_user', 'username',
               existing_type=sa.VARCHAR(length=50),
               comment='用户名',
               existing_nullable=False)
    op.alter_column('auth_user', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='邮箱',
               existing_nullable=True)
    op.alter_column('auth_user', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='手机号',
               existing_nullable=True)
    op.alter_column('auth_user', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='密码哈希',
               existing_nullable=False)
    op.alter_column('auth_user', 'tenant_id',
               existing_type=sa.UUID(),
               comment='租户ID',
               existing_nullable=False)
    op.alter_column('auth_user', 'role',
               existing_type=sa.VARCHAR(length=50),
               comment='用户角色',
               existing_nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    op.alter_column('auth_user', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否激活',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('auth_user', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               comment='是否超级用户',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('auth_user', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='创建时间')
    op.alter_column('auth_user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='更新时间')
    # Drop indexes only if they exist
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM pg_indexes
                WHERE tablename = 'messages'
                AND indexname = 'message_end_user_idx'
            ) THEN
                DROP INDEX message_end_user_idx;
            END IF;
        END $$;
    """)
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM pg_indexes
                WHERE tablename = 'messages'
                AND indexname = 'message_workflow_run_id_idx'
            ) THEN
                DROP INDEX message_workflow_run_id_idx;
            END IF;
        END $$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('message_workflow_run_id_idx'), 'messages', ['conversation_id', 'workflow_run_id'], unique=False)
    op.create_index(op.f('message_end_user_idx'), 'messages', ['app_id', 'from_source', 'from_end_user_id'], unique=False)
    op.alter_column('auth_user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='更新时间')
    op.alter_column('auth_user', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='创建时间')
    op.alter_column('auth_user', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否超级用户',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('auth_user', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否激活',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('auth_user', 'role',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='用户角色',
               existing_nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    op.alter_column('auth_user', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='租户ID',
               existing_nullable=False)
    op.alter_column('auth_user', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='密码哈希',
               existing_nullable=False)
    op.alter_column('auth_user', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='手机号',
               existing_nullable=True)
    op.alter_column('auth_user', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='邮箱',
               existing_nullable=True)
    op.alter_column('auth_user', 'username',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='用户名',
               existing_nullable=False)
    op.alter_column('auth_tenant', 'admin_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='管理员ID',
               existing_nullable=True)
    op.alter_column('auth_tenant', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='更新时间')
    op.alter_column('auth_tenant', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='创建时间')
    op.alter_column('auth_tenant', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否激活',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('auth_tenant', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True,
               comment=None,
               existing_comment='租户描述')
    op.alter_column('auth_tenant', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='租户名称',
               existing_nullable=False)
    op.alter_column('app', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('app', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('app', 'version',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='版本号',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('app', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Agent参数配置',
               existing_nullable=True)
    op.alter_column('app', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否启用',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('app', 'app_code',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='对外使用的agent标识',
               existing_nullable=False)
    op.alter_column('agent_template', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('agent_template', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('agent_template', 'version',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='版本号',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('agent_template', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Agent参数配置',
               existing_nullable=True)
    op.alter_column('agent_template', 'enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否启用',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('agent_template', 'template_name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='模板名称',
               existing_nullable=False)
    op.alter_column('agent_template', 'template_code',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='模板标识',
               existing_nullable=False)
    op.create_foreign_key(op.f('fk_agent_task_app'), 'agent_task', 'app', ['app_id'], ['id'], ondelete='CASCADE')
    op.alter_column('agent_task', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('agent_task', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='开始执行时间',
               existing_nullable=True)
    op.alter_column('agent_task', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('agent_task', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('agent_task', 'progress',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='任务进度百分比',
               existing_nullable=True)
    op.alter_column('agent_task', 'error',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='错误信息',
               existing_nullable=True)
    op.alter_column('agent_task', 'result',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='任务结果',
               existing_nullable=True)
    op.alter_column('agent_task', 'text_message',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='任务输入数据',
               existing_nullable=True)
    op.alter_column('agent_task', 'status',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='任务状态: pending, running, success, failed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('agent_task', 'task_type',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='任务类型',
               existing_nullable=True)
    op.alter_column('agent_task', 'app_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='关联的agent标识',
               existing_nullable=False)
    # ### end Alembic commands ###
