"""add app_id to event table

Revision ID: 32bf5fe1f194
Revises: 20260301_baseline
Create Date: 2026-02-13 21:09:40.892426

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '32bf5fe1f194'
down_revision: str | Sequence[str] | None = '20260301_baseline'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('app_id', sa.UUID(), nullable=True, comment='关联的应用ID'))
    op.create_foreign_key(None, 'event', 'app', ['app_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'app_id')
    # ### end Alembic commands ###
