"""remove_file_hash_unique_constraint

Revision ID: 3a54b027c7d6
Revises: d44c36b57007
Create Date: 2026-01-25 19:46:40.333983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3a54b027c7d6'
down_revision: Union[str, Sequence[str], None] = 'd44c36b57007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'file_hash',
                    existing_type=sa.VARCHAR(length=64),
                    comment='SHA256哈希',
                    existing_comment='SHA256哈希，用于去重',
                    existing_nullable=True)
    op.drop_constraint(op.f('document_file_hash_key'), 'document', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('document_file_hash_key'), 'document', ['file_hash'],
                                postgresql_nulls_not_distinct=False)
    op.alter_column('document', 'file_hash',
                    existing_type=sa.VARCHAR(length=64),
                    comment='SHA256哈希，用于去重',
                    existing_comment='SHA256哈希',
                    existing_nullable=True)
    # ### end Alembic commands ###
