"""create workspace_context table

Revision ID: 7f5f41cd5b30
Revises: d53fb5f02f6b
Create Date: 2026-02-14 21:07:45.956972

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f5f41cd5b30'
down_revision: str | Sequence[str] | None = 'd53fb5f02f6b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_context',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False, comment='所属工作空间ID'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='创建者用户ID'),
    sa.Column('path', sa.String(length=1024), nullable=True, comment='虚拟文件路径，用于按层级管理上下文'),
    sa.Column('name', sa.String(length=512), nullable=False, comment='上下文条目名称'),
    sa.Column('content_type', sa.String(length=128), nullable=True, comment='内容MIME类型'),
    sa.Column('content', sa.Text(), nullable=True, comment='上下文内容（小型文本直接存储）'),
    sa.Column('s3_key', sa.String(length=1024), nullable=True, comment='S3对象键，用于获取实际内容'),
    sa.Column('size_bytes', sa.Integer(), nullable=True, comment='内容大小（字节）'),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='额外元数据'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='过期时间（临时上下文自动清理）'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ws_ctx_created_by', 'workspace_context', ['created_by'], unique=False)
    op.create_index('ix_ws_ctx_expires', 'workspace_context', ['expires_at'], unique=False)
    op.create_index('ix_ws_ctx_workspace', 'workspace_context', ['workspace_id'], unique=False)
    op.create_index('ix_ws_ctx_workspace_path', 'workspace_context', ['workspace_id', 'path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ws_ctx_workspace_path', table_name='workspace_context')
    op.drop_index('ix_ws_ctx_workspace', table_name='workspace_context')
    op.drop_index('ix_ws_ctx_expires', table_name='workspace_context')
    op.drop_index('ix_ws_ctx_created_by', table_name='workspace_context')
    op.drop_table('workspace_context')
    # ### end Alembic commands ###
