"""

Revision ID: 8e930fc7b4e3
Revises: eb254ab4cc1b
Create Date: 2026-02-18 20:02:10.040235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e930fc7b4e3'
down_revision: Union[str, Sequence[str], None] = 'eb254ab4cc1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace_trigger', sa.Column('user_id', sa.UUID(), nullable=True, comment='创建者用户ID（用于用户级模板）'))
    op.alter_column('workspace_trigger', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment='所属工作区ID（用户级模板时为 null）',
               existing_comment='所属工作区ID')
    op.create_index(op.f('ix_workspace_trigger_user_id'), 'workspace_trigger', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_trigger_user_id'), table_name='workspace_trigger')
    op.alter_column('workspace_trigger', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment='所属工作区ID',
               existing_comment='所属工作区ID（用户级模板时为 null）')
    op.drop_column('workspace_trigger', 'user_id')
    # ### end Alembic commands ###
