"""add user_tools table

Add user_tools table for storing user-defined custom tools.
Supports multiple execution modes: server_run, http, client_run, container_run, celery_run.

Revision ID: 93ba21f038ef
Revises: add_executor_code_001
Create Date: 2026-02-08 14:05:52.111434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93ba21f038ef'
down_revision: Union[str, Sequence[str], None] = 'add_executor_code_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Tool owner ID'),
    sa.Column('workspace_id', sa.UUID(), nullable=True, comment='Workspace ID (optional)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Tool name (unique per user)'),
    sa.Column('display_name', sa.String(length=200), nullable=False, comment='Display name'),
    sa.Column('description', sa.Text(), nullable=False, comment='Tool description'),
    sa.Column('execution_mode', sa.String(length=50), nullable=False, comment='Execution mode: server_run, http, client_run, container_run, celery_run'),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Input parameters schema (Pydantic format)'),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Output schema (optional)'),
    sa.Column('code', sa.Text(), nullable=True, comment='Python code for server_run mode'),
    sa.Column('http_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='HTTP configuration for http mode'),
    sa.Column('container_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Container configuration for container_run mode'),
    sa.Column('client_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Client configuration for client_run mode'),
    sa.Column('celery_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Celery configuration for celery_run mode'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='Tool category'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Tool tags'),
    sa.Column('version', sa.String(length=20), nullable=False, comment='Tool version'),
    sa.Column('timeout', sa.Integer(), nullable=False, comment='Execution timeout in seconds'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='Whether tool is enabled'),
    sa.Column('is_public', sa.Boolean(), nullable=False, comment='Whether tool is public (shared with others)'),
    sa.Column('verified', sa.Boolean(), nullable=False, comment='Whether tool is verified by admin'),
    sa.Column('usage_count', sa.Integer(), nullable=False, comment='Number of times tool has been used'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='Last used timestamp'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Created at'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Updated at'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_tools_enabled', 'user_tools', ['enabled'], unique=False)
    op.create_index('ix_user_tools_is_public', 'user_tools', ['is_public'], unique=False)
    op.create_index('ix_user_tools_name', 'user_tools', ['name'], unique=False)
    op.create_index('ix_user_tools_user_id', 'user_tools', ['user_id'], unique=False)
    op.create_index('ix_user_tools_user_name', 'user_tools', ['user_id', 'name'], unique=True)
    op.create_index('ix_user_tools_workspace_id', 'user_tools', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_tools_workspace_id', table_name='user_tools')
    op.drop_index('ix_user_tools_user_name', table_name='user_tools')
    op.drop_index('ix_user_tools_user_id', table_name='user_tools')
    op.drop_index('ix_user_tools_name', table_name='user_tools')
    op.drop_index('ix_user_tools_is_public', table_name='user_tools')
    op.drop_index('ix_user_tools_enabled', table_name='user_tools')
    op.drop_table('user_tools')
    # ### end Alembic commands ###
