"""add progressive disclosure fields to context models

Revision ID: c9e09d25a17f
Revises: 7f5f41cd5b30
Create Date: 2026-02-15 19:57:42.363953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9e09d25a17f'
down_revision: Union[str, Sequence[str], None] = '7f5f41cd5b30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('context', sa.Column('glance', sa.String(length=512), nullable=True, comment='一句话摘要（扫描层，快速浏览用）'))
    op.add_column('context', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='标签列表，用于分类和过滤'))
    op.alter_column('context', 'summary',
               existing_type=sa.TEXT(),
               comment='概览摘要（概览层，结构化数据）',
               existing_comment='上下文摘要',
               existing_nullable=True)
    op.alter_column('context', 'content',
               existing_type=sa.TEXT(),
               comment='完整内容（详情层）',
               existing_comment='上下文内容',
               existing_nullable=False)
    op.alter_column('context', 'keywords',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='关键词（已弃用，请使用 tags）',
               existing_comment='关键词',
               existing_nullable=True)
    op.create_index('ix_context_glance', 'context', ['glance'], unique=False)
    op.create_index('ix_context_user_path', 'context', ['user_id', 'path'], unique=False)
    op.add_column('workspace_context', sa.Column('glance', sa.String(length=512), nullable=True, comment='一句话摘要（扫描层）'))
    op.add_column('workspace_context', sa.Column('summary', sa.Text(), nullable=True, comment='概览摘要（概览层）'))
    op.add_column('workspace_context', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='标签列表，用于分类和过滤'))
    op.alter_column('workspace_context', 'content',
               existing_type=sa.TEXT(),
               comment='完整内容（详情层，小型文本直接存储）',
               existing_comment='上下文内容（小型文本直接存储）',
               existing_nullable=True)
    op.create_index('ix_ws_ctx_glance', 'workspace_context', ['glance'], unique=False)
    op.create_index('ix_ws_ctx_workspace_deleted', 'workspace_context', ['workspace_id', 'is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ws_ctx_workspace_deleted', table_name='workspace_context')
    op.drop_index('ix_ws_ctx_glance', table_name='workspace_context')
    op.alter_column('workspace_context', 'content',
               existing_type=sa.TEXT(),
               comment='上下文内容（小型文本直接存储）',
               existing_comment='完整内容（详情层，小型文本直接存储）',
               existing_nullable=True)
    op.drop_column('workspace_context', 'tags')
    op.drop_column('workspace_context', 'summary')
    op.drop_column('workspace_context', 'glance')
    op.drop_index('ix_context_user_path', table_name='context')
    op.drop_index('ix_context_glance', table_name='context')
    op.alter_column('context', 'keywords',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='关键词',
               existing_comment='关键词（已弃用，请使用 tags）',
               existing_nullable=True)
    op.alter_column('context', 'content',
               existing_type=sa.TEXT(),
               comment='上下文内容',
               existing_comment='完整内容（详情层）',
               existing_nullable=False)
    op.alter_column('context', 'summary',
               existing_type=sa.TEXT(),
               comment='上下文摘要',
               existing_comment='概览摘要（概览层，结构化数据）',
               existing_nullable=True)
    op.drop_column('context', 'tags')
    op.drop_column('context', 'glance')
    # ### end Alembic commands ###
