"""add progressive disclosure fields to context models

Revision ID: c9e09d25a17f
Revises: 7f5f41cd5b30
Create Date: 2026-02-15 19:57:42.363953

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9e09d25a17f'
down_revision: str | Sequence[str] | None = '7f5f41cd5b30'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(sa.text("ALTER TABLE context ADD COLUMN IF NOT EXISTS glance VARCHAR(512)"))
    conn.execute(sa.text("ALTER TABLE context ADD COLUMN IF NOT EXISTS tags JSONB"))
    conn.execute(sa.text("ALTER TABLE context ADD COLUMN IF NOT EXISTS summary TEXT"))
    op.alter_column('context', 'summary',
               existing_type=sa.TEXT(),
               comment='概览摘要（概览层，结构化数据）',
               existing_nullable=True)
    op.alter_column('context', 'content',
               existing_type=sa.TEXT(),
               comment='完整内容（详情层）',
               existing_nullable=False)
    conn.execute(sa.text("ALTER TABLE context ADD COLUMN IF NOT EXISTS keywords JSONB"))
    op.alter_column('context', 'keywords',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='关键词（已弃用，请使用 tags）',
               existing_nullable=True)
    conn.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_context_glance ON context (glance)"))
    conn.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_context_user_path ON context (user_id, path)"))
    conn.execute(sa.text("ALTER TABLE workspace_context ADD COLUMN IF NOT EXISTS glance VARCHAR(512)"))
    conn.execute(sa.text("ALTER TABLE workspace_context ADD COLUMN IF NOT EXISTS summary TEXT"))
    conn.execute(sa.text("ALTER TABLE workspace_context ADD COLUMN IF NOT EXISTS tags JSONB"))
    op.alter_column('workspace_context', 'content',
               existing_type=sa.TEXT(),
               comment='完整内容（详情层，小型文本直接存储）',
               existing_nullable=True)
    conn.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_ws_ctx_glance ON workspace_context (glance)"))
    conn.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_ws_ctx_workspace_deleted ON workspace_context (workspace_id, is_deleted)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ws_ctx_workspace_deleted', table_name='workspace_context')
    op.drop_index('ix_ws_ctx_glance', table_name='workspace_context')
    op.alter_column('workspace_context', 'content',
               existing_type=sa.TEXT(),
               comment='上下文内容（小型文本直接存储）',
               existing_comment='完整内容（详情层，小型文本直接存储）',
               existing_nullable=True)
    op.drop_column('workspace_context', 'tags')
    op.drop_column('workspace_context', 'summary')
    op.drop_column('workspace_context', 'glance')
    op.drop_index('ix_context_user_path', table_name='context')
    op.drop_index('ix_context_glance', table_name='context')
    op.alter_column('context', 'keywords',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='关键词',
               existing_comment='关键词（已弃用，请使用 tags）',
               existing_nullable=True)
    op.alter_column('context', 'content',
               existing_type=sa.TEXT(),
               comment='上下文内容',
               existing_comment='完整内容（详情层）',
               existing_nullable=False)
    op.alter_column('context', 'summary',
               existing_type=sa.TEXT(),
               comment='上下文摘要',
               existing_comment='概览摘要（概览层，结构化数据）',
               existing_nullable=True)
    op.drop_column('context', 'tags')
    op.drop_column('context', 'glance')
    # ### end Alembic commands ###
