"""add_document_status_fields

Revision ID: d44c36b57007
Revises: 477f1f668530
Create Date: 2026-01-25 14:43:38.860553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd44c36b57007'
down_revision: Union[str, Sequence[str], None] = '477f1f668530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns with server defaults for existing rows
    op.add_column('document', sa.Column('status', sa.String(length=20), nullable=False, server_default='pending',
                                        comment='处理状态: pending/processing/completed/failed'))
    op.add_column('document', sa.Column('error_message', sa.Text(), nullable=True, comment='处理错误信息'))
    op.add_column('document',
                  sa.Column('chunk_count', sa.Integer(), nullable=False, server_default='0', comment='分块数量'))

    # Remove server defaults after migration (optional, to match model definition)
    op.alter_column('document', 'status', server_default=None)
    op.alter_column('document', 'chunk_count', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'chunk_count')
    op.drop_column('document', 'error_message')
    op.drop_column('document', 'status')
    # ### end Alembic commands ###
