"""add path and s3_key to context table

Revision ID: d53fb5f02f6b
Revises: 32bf5fe1f194
Create Date: 2026-02-14 21:04:47.694256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd53fb5f02f6b'
down_revision: Union[str, Sequence[str], None] = '32bf5fe1f194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('context', sa.Column('path', sa.String(length=1024), nullable=True, comment='虚拟文件夹路径，用于按层级管理上下文'))
    op.add_column('context', sa.Column('s3_key', sa.String(length=1024), nullable=True, comment='S3对象键，用于获取上下文的实际内容'))
    op.create_index('ix_context_path', 'context', ['path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_context_path', table_name='context')
    op.drop_column('context', 's3_key')
    op.drop_column('context', 'path')
    # ### end Alembic commands ###
