"""

Revision ID: eb254ab4cc1b
Revises: b2f3e4c5d6e7
Create Date: 2026-02-18 19:46:47.236708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb254ab4cc1b'
down_revision: Union[str, Sequence[str], None] = 'b2f3e4c5d6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(sa.text("""
        CREATE TABLE IF NOT EXISTS workspace_trigger (
            id UUID NOT NULL,
            workspace_id UUID,
            name VARCHAR(255) NOT NULL,
            description TEXT,
            event_type VARCHAR(100) NOT NULL,
            condition_type VARCHAR(50) NOT NULL,
            condition_value TEXT,
            condition_field VARCHAR(255),
            action_type VARCHAR(100),
            action_params JSONB,
            priority INTEGER NOT NULL,
            enabled BOOLEAN NOT NULL,
            created_by UUID,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ,
            PRIMARY KEY (id)
        )
    """))
    conn.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_workspace_trigger_workspace_id ON workspace_trigger (workspace_id)"))
    conn.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_workspace_trigger_ws_event ON workspace_trigger (workspace_id, event_type, enabled)"))
    conn.execute(sa.text("DROP INDEX IF EXISTS ix_skill_user_id"))
    conn.execute(sa.text("DROP INDEX IF EXISTS ix_skill_user_id_name"))
    conn.execute(sa.text("DROP TABLE IF EXISTS skill"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('glance', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('source_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('skill_pkey'))
    )
    op.create_index(op.f('ix_skill_user_id_name'), 'skill', ['user_id', 'name'], unique=False)
    op.create_index(op.f('ix_skill_user_id'), 'skill', ['user_id'], unique=False)
    op.drop_index('ix_workspace_trigger_ws_event', table_name='workspace_trigger')
    op.drop_index(op.f('ix_workspace_trigger_workspace_id'), table_name='workspace_trigger')
    op.drop_table('workspace_trigger')
    # ### end Alembic commands ###
