"""

Revision ID: eb254ab4cc1b
Revises: b2f3e4c5d6e7
Create Date: 2026-02-18 19:46:47.236708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb254ab4cc1b'
down_revision: Union[str, Sequence[str], None] = 'b2f3e4c5d6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_trigger',
    sa.Column('id', sa.UUID(), nullable=False, comment='触发器唯一标识'),
    sa.Column('workspace_id', sa.UUID(), nullable=False, comment='所属工作区ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='触发器名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='触发器描述'),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment='监听的事件类型，如 user.message'),
    sa.Column('condition_type', sa.String(length=50), nullable=False, comment='条件类型: always | keyword | regex | jsonpath'),
    sa.Column('condition_value', sa.Text(), nullable=True, comment='条件表达式（关键字/正则/JSONPath）'),
    sa.Column('condition_field', sa.String(length=255), nullable=True, comment='检查的 payload 字段名，默认 message，支持点记法如 data.text'),
    sa.Column('action_type', sa.String(length=100), nullable=False, comment='动作类型: read_context | list_context | glance_context | glob_context | search_context'),
    sa.Column('action_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="动作参数，如 {'prefix': 'tools'}"),
    sa.Column('priority', sa.Integer(), nullable=False, comment='优先级（数值越小优先级越高）'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='创建者用户ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_trigger_workspace_id'), 'workspace_trigger', ['workspace_id'], unique=False)
    op.create_index('ix_workspace_trigger_ws_event', 'workspace_trigger', ['workspace_id', 'event_type', 'enabled'], unique=False)
    op.drop_index(op.f('ix_skill_user_id'), table_name='skill')
    op.drop_index(op.f('ix_skill_user_id_name'), table_name='skill')
    op.drop_table('skill')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('glance', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('source_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('skill_pkey'))
    )
    op.create_index(op.f('ix_skill_user_id_name'), 'skill', ['user_id', 'name'], unique=False)
    op.create_index(op.f('ix_skill_user_id'), 'skill', ['user_id'], unique=False)
    op.drop_index('ix_workspace_trigger_ws_event', table_name='workspace_trigger')
    op.drop_index(op.f('ix_workspace_trigger_workspace_id'), table_name='workspace_trigger')
    op.drop_table('workspace_trigger')
    # ### end Alembic commands ###
