"""add tool registry table

Revision ID: f08172d65fba
Revises: 20260304_ws_app_id
Create Date: 2026-02-07 09:19:35.926333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f08172d65fba'
down_revision: Union[str, Sequence[str], None] = '20260304_ws_app_id'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='工具名称'),
    sa.Column('tool_code', sa.String(length=100), nullable=False, comment='工具唯一标识'),
    sa.Column('description', sa.Text(), nullable=True, comment='工具描述'),
    sa.Column('tool_type', sa.String(length=20), server_default='server', nullable=False, comment='工具执行类型: server, sandbox, client, async'),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='工具输入参数的JSON Schema定义'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='工具执行配置(沙箱镜像、客户端处理器等)'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='创建该工具的用户ID'),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False, comment='是否启用'),
    sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False, comment='是否公开可用'),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False, comment='版本号'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_code')
    )
    op.alter_column('run', 'app_id',
               existing_type=sa.UUID(),
               comment='应用ID',
               existing_nullable=True)
    op.alter_column('workspace', 'app_id',
               existing_type=sa.UUID(),
               comment='默认应用ID',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspace', 'app_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='默认应用ID',
               existing_nullable=True)
    op.alter_column('run', 'app_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='应用ID',
               existing_nullable=True)
    op.drop_table('tool')
    # ### end Alembic commands ###
