"""add inner_tool_name and parameter_mapping to user_tools

Revision ID: fc7024d34fc3
Revises: 93ba21f038ef
Create Date: 2026-02-09 15:14:44.205677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc7024d34fc3'
down_revision: Union[str, Sequence[str], None] = '93ba21f038ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tools', sa.Column('inner_tool_name', sa.String(length=100), nullable=True, comment='Name of the InnerTool to delegate to (overrides execution_mode-based default)'))
    op.add_column('user_tools', sa.Column('parameter_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Maps external param names to InnerTool param names (1:1 mapping)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tools', 'parameter_mapping')
    op.drop_column('user_tools', 'inner_tool_name')
    # ### end Alembic commands ###
